Traceback (most recent call last):
  File "C:\Users\Jordan\Learning\UVM\Research\novel-feature-detector\evolution.py", line 214, in <module>
    run()
  File "C:\Users\Jordan\Learning\UVM\Research\novel-feature-detector\evolution.py", line 149, in run
    data_module.setup()
  File "C:\Users\Jordan\anaconda3\envs\EC2\lib\site-packages\pl_bolts\datamodules\vision_datamodule.py", line 74, in setup
    dataset_train = self.dataset_cls(self.data_dir, train=True, transform=train_transforms, **self.EXTRA_ARGS)
  File "C:\Users\Jordan\anaconda3\envs\EC2\lib\site-packages\torchvision\datasets\cifar.py", line 68, in __init__
    raise RuntimeError("Dataset not found or corrupted. You can use download=True to download it")
RuntimeError: Dataset not found or corrupted. You can use download=True to download it